---
pull_request_rules:
  - name: Merge dependabot PRs when all checks pass
    conditions:
      - and:
        - author~=^dependabot(|-preview)\[bot\]$
        - check-success=SonarCloud Code Analysis
        - check-success~=^security/snyk
        - check-success=🧹 Lint
        - label!=wontfix
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot
      merge:
        method: merge
  - name: Merge when all checks pass and the PR has been approved
    conditions:
      - and:
        - check-success~=^security/snyk
        - check-success=SonarCloud Code Analysis
        - check-success=🧹 Lint
        - "#approved-reviews-by>=1"
        - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: merge
